apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: dev-cluster # 不能有下划线
servers: 1
agents: 3
kubeAPI:
  hostPort: "6443" 
ports:
  - port: 8080:80  # ingress端口映射
    nodeFilters:
      - loadbalancer
  - port: 8443:443 
    nodeFilters:
      - loadbalancer